package macaroni

import (
	"context"
	"testing"

	"github.com/psyark/recipebot/rexch"
	"github.com/psyark/recipebot/sites"
)

// TODO: 実装
var tests = map[string]*rexch.Recipe{
	"https://macaro-ni.jp/109611": nil,
	// "https://macaro-ni.jp/90067":  `{"Title":"わさびがポイント！お豆腐の大葉肉巻き","Image":"https://cdn.macaro-ni.jp/image/summary/90/90067/yw8njYPbCLPv97YaraNnNyHQQuliiNRYuGHAV9My.jpeg?p=1x1","IngredientGroups":[{"Name":"","Children":[{"Name":"木綿豆腐","Amount":"300g","Comment":""},{"Name":"豚バラ肉","Amount":"200g","Comment":"薄切り"},{"Name":"大葉","Amount":"10枚","Comment":""},{"Name":"片栗粉","Amount":"適量","Comment":""},{"Name":"わさび","Amount":"大さじ1/2杯","Comment":""},{"Name":"サラダ油","Amount":"適量","Comment":""}]},{"Name":"a.","Children":[{"Name":"酒","Amount":"大さじ1杯","Comment":""},{"Name":"みりん","Amount":"大さじ1杯","Comment":""},{"Name":"砂糖","Amount":"大さじ1杯","Comment":""},{"Name":"しょうゆ","Amount":"大さじ2杯","Comment":""}]}],"Steps":[{"Text":"豆腐をキッチンペーパーでくるみ、レンジ600Wで3分加熱します。","Images":["https://cdn.macaro-ni.jp/image/summary/90/90067/ekhmUcHBt9BZjyjMkeQ0anUcPf4zDwiW50cJkbuj.jpeg"]},{"Text":"重石をして10分ほどおき、しっかり水切りをして1cm幅に切ります。","Images":["https://cdn.macaro-ni.jp/image/summary/90/90067/xxt0MRAfIq3cBn552blhp3Z62sEyFiAkESYLBhlX.jpeg"]},{"Text":"豚肉に大葉、豆腐をのせて巻き上げ、片栗粉をまぶします。","Images":["https://cdn.macaro-ni.jp/image/summary/90/90067/lxE9asgFlMtHHYFNYxXglLhX49x8ujwJqgkkQDVi.jpeg"]},{"Text":"フライパンにサラダ油を引いて熱し、③を並べて焼き色がつくまで焼きます。","Images":["https://cdn.macaro-ni.jp/image/summary/90/90067/lHi9RkopTzOU57FWnoNN0JVPPpkCjpf4Gf9XQyqZ.jpeg"]},{"Text":"(a) を加えて全体がからんだら火を弱め、わさびを加えて全体にからめたら完成です。","Images":["https://cdn.macaro-ni.jp/image/summary/90/90067/x3UpTsrLKH0C4o4VilxiiVJrABJdbC76jeDHm75h.jpeg"]}]}`,
	// "https://macaro-ni.jp/85520":  `{"Title":"メイン食材1つ。豆腐のスティックフライ","Image":"https://cdn.macaro-ni.jp/image/summary/85/85520/488fa7c470eb630b98de98fc66548774.jpg?p=1x1","IngredientGroups":[{"Name":"","Children":[{"Name":"木綿豆腐","Amount":"200g","Comment":""},{"Name":"片栗粉","Amount":"適量","Comment":""},{"Name":"サラダ油","Amount":"適量","Comment":""},{"Name":"塩","Amount":"少々","Comment":""},{"Name":"粗挽き黒こしょう","Amount":"少々","Comment":""},{"Name":"ガーリックパウダー","Amount":"少々","Comment":""}]}],"Steps":[{"Text":"キッチンペーパーで豆腐を包み、耐熱皿にのせて電子レンジ500Ｗ3分加熱し、水切りをします。","Images":null},{"Text":"取り出したら1cm角の棒状に切ります。","Images":null},{"Text":"片栗粉を全体にまぶします。","Images":null},{"Text":"フライパンに170℃のサラダ油を熱し、③を加えて揚げ焼きにします。","Images":null},{"Text":"油をよく切り、塩、こしょう、ガーリックパウダーを振ったら完成です。","Images":null}]}`,
	// "https://macaro-ni.jp/35774":  `{"Title":"必見！コツをおさえた『基本の鮭フライ＆タルタルソース』の作り方","Image":"https://cdn.macaro-ni.jp/image/summary/35/35774/2a8f6aae712a66cdf5c8485a93a3f044.jpg?p=medium","IngredientGroups":null,"Steps":[{"Text":"\n①鮭は食べやすいよう、1切れを2〜3切れに切る。\n②塩胡椒(分量外)を全体にまんべんなく振り、5分ほど置く。水分が出るのでキッチンペーパー等で軽く拭きとる。\n塩胡椒を振って水分を出すことで生臭みを取るので、必ずこの行程は行いましょう。\nまた、塩を振ることで旨味も増します。\n③袋に鮭と薄力粉を入れ、薄力粉を全体にまぶす。\n空気を含んだ状態で口を閉じ、全体を揺するようにすると薄力粉がきれいに付きます。\n④袋から鮭を取り出し、一つずつ軽く叩いて余分な薄力粉を落とす。\n薄力粉・卵・パン粉の3つとも、余分に付いていると揚げた時にムラができます。\nきれいな仕上がりにするために、軽く叩きましょう。\n⑤鮭を卵にくぐらせる。\n薄力粉と同じく、卵はくぐらせた後によく水気を切りましょう。\n⑥粉チーズを混ぜたパン粉に鮭をのせ、パン粉を全体によくまぶす。\nパン粉を付けたら、鮭は軽く振って余分なパン粉を落とし、別の容器に置きましょう。\n⑦170℃に熱した油で、きつね色になるまでじっくり揚げる。\n火加減の目安は中火です。油が十分に温まり、なおかつ高温すぎないのがポイント。\n⑧ふちがきつね色になったらひっくり返し、反対側も同じように揚げる。\nふちがきつね色になってからひっくり返すと、火加減が均等で色も良く仕上がります。\nひっくり返す時に、衣が硬くサクッとしていればOK。\n衣が柔らかい場合は火が弱いので、火加減を調整しましょう。\n⑨バットに上げて、余分な油を落とす。\n油切れが悪いと、ベタついたり胃もたれの原因になります。\n必ず油を落としましょう。\n次にタルタルソースを作ります。\n⑩玉ねぎはみじん切りにして、水にさらす。\n玉ねぎの辛味を抜きます。時間がない場合は、みじん切りして塩をまぶし、軽く握りつぶしてから水にさらすと繊維が潰れて辛味が早く抜けます。\n⑪茹で卵をフォーク等で潰す。\n⑫茹で卵、水気を切った玉ねぎにBの材料を加え、よく混ぜ合わせる。","Images":["https://cdn.macaro-ni.jp/image/summary/35/35774/567f5cb41b2286ae60d4d50922f023b9.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/c7e74110c599d13774d13970fdad4d06.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/6a9cde73befc66ba24908e8d83b39c63.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/00bfda22dee251416d728d9c2c7cdded.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/28d95776755897528b210f32c65f6e34.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/a12119be3895d3041acf3bf1898244cf.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/8095dd34daaa3e9e013297131193770c.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/d7358658a5b263523fdb003fb0a4ee04.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/40a21368c402b5b0d98c0f35a0723550.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/854e7a24b157f83b5bb4789e137cfa9c.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/b820fa7fcd527d067253ca6a4a0160af.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/8b82745ef832ea1a7c2dc8194821695f.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/489ae3463574a9953ff59d25120f4c70.jpg?p=medium"]},{"Text":"ぜひ揚げたての食感を楽しんで！\n揚げたてのサクサクをお召し上がりください。\nお好みでレモンを絞ると、より爽やかに頂けます。\nタルタルソースはたっぷりかけるのが美味しさの秘訣！\nタルタルソースのみでも、レモンをプラスしても、さらにソースをかけても美味しいです。\n\nビールと一緒に食べると最高！揚げた後に油をしっかり落とせば、油やけの心配もありません。\n\nタルタルソースはお好みでキュウリのみじん切りやピクルス等を入れて、食感の変化をお楽しみください。","Images":["https://cdn.macaro-ni.jp/image/summary/35/35774/58a32da160ee9b7f1b5d66241874a551.jpg?p=medium","https://cdn.macaro-ni.jp/image/summary/35/35774/9590d4298b5153378bebb6584810ea9c.jpg?p=medium"]}]}`,
	// "https://macaro-ni.jp/45500":  `{"Title":"ごはん無限レベル！豚肉とれんこんの甘辛炒め【作り置き】","Image":"https://cdn.macaro-ni.jp/image/summary/45/45500/7d761cc229abdcb5088e77942c7bc1ed.jpg?p=1x1","IngredientGroups":[{"Name":"","Children":[{"Name":"豚こま切れ肉","Amount":"300g","Comment":""},{"Name":"れんこん","Amount":"200g","Comment":""},{"Name":"片栗粉","Amount":"大さじ2杯","Comment":"豚肉用"},{"Name":"片栗粉","Amount":"大さじ2杯","Comment":"れんこん用"},{"Name":"塩こしょう","Amount":"少々","Comment":"豚肉下味用"},{"Name":"サラダ油","Amount":"適量","Comment":""},{"Name":"☆砂糖","Amount":"大さじ3杯","Comment":""},{"Name":"☆しょうゆ","Amount":"大さじ3杯","Comment":""},{"Name":"☆酢","Amount":"大さじ3杯","Comment":""},{"Name":"白ごま","Amount":"適量","Comment":""}]}],"Steps":[{"Text":"豚こま切れ肉とれんこんに片栗粉を大さじ2杯ずつまぶします。","Images":null},{"Text":"フライパンにサラダ油を深さ3cm入れて170℃に熱し、れんこんを揚げ焼きにします。まぶした片栗粉がカリっとしてきたら油から上げます。","Images":null},{"Text":"次に豚こま切れ肉を入れて揚げ焼きにし、カリカリになったら油を切って上げます。","Images":null},{"Text":"フライパンの油をふき取り☆の調味料を入れてひと煮立ちさせます。とろみがついたら②のれんこんと③の豚こま切れ肉を加えて絡めます。","Images":null},{"Text":"保存容器に入れ、お好みで白ごまを振って完成です！保存期間は冷蔵5日間です♪","Images":null}]}`,
	// "https://macaro-ni.jp/104118": `{"Title":"ランチにも♪ 豚こまガーリックライス","Image":"https://cdn.macaro-ni.jp/image/summary/104/104118/P55cvVVOQNXc4ze0Q967VN79JtjAPAOSrwNTSZAJ.jpg?p=1x1","IngredientGroups":[{"Name":"","Children":[{"Name":"豚こま肉","Amount":"120g","Comment":""},{"Name":"ごはん","Amount":"400g","Comment":""},{"Name":"にんにく","Amount":"2片","Comment":""},{"Name":"塩","Amount":"少々","Comment":""},{"Name":"黒こしょう","Amount":"少々","Comment":""},{"Name":"にんにく","Amount":"小さじ1杯","Comment":"すりおろし"},{"Name":"しょうゆ","Amount":"小さじ2杯","Comment":""},{"Name":"ウスターソース","Amount":"小さじ1杯","Comment":""},{"Name":"サラダ油","Amount":"大さじ1杯","Comment":""},{"Name":"トッピング","Amount":"","Comment":""},{"Name":"黒こしょう","Amount":"適量","Comment":""},{"Name":"ドライパセリ","Amount":"適量","Comment":""}]}],"Steps":[{"Text":"にんにくの両端を切り落とします。爪楊枝で芯の小さい方から大きい方に向かって、爪楊枝の太い方を使って押し出します。薄切りします。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104118/j4VGePFKJdYYNAIRCbhlmhcOkfuaN6XPDroqGyi3.jpg"]},{"Text":"フライパンにサラダ油、にんにくをいれて弱火で熱します。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104118/bIo25QPs7WJVrvzJJ1nXiQx30um7m5Y82ajCWn5o.jpg"]},{"Text":"にんにくに色がついたら取り出し、豚こま肉、塩、黒こしょうを入れて中火で炒めます。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104118/uF8b5bROiuYF0tMb06SUlICuMEbZW62yIjq9LN28.jpg"]},{"Text":"豚肉の色が変わってきたらごはんを加えて強火で炒めます。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104118/GhzdktAdSNfsgB5ZYEMdUihEhbXbwYdS6JSwZoO6.jpg"]},{"Text":"すりおろしにんにく、しょうゆ、ウスターソースを加えて混ぜ合わせて完成です。器に盛り付けてお好みでパセリ、黒こしょうをトッピングして完成です。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104118/RursIk492XUUqqXf0QbOtJrO9QlIb0kEcaN0z9tW.jpg"]}]}`,
	// "https://macaro-ni.jp/84903":  `{"Title":"油揚げで簡単。豚こまとんかつ","Image":"https://cdn.macaro-ni.jp/image/summary/84/84903/2HcJACf7b2xi6FMYZqRyjxHRWUb7O6bUxTBcgO3r.jpeg?p=1x1","IngredientGroups":[{"Name":"","Children":[{"Name":"豚こま肉","Amount":"240g","Comment":""},{"Name":"油揚げ","Amount":"2枚","Comment":""},{"Name":"塩","Amount":"少々","Comment":""},{"Name":"こしょう","Amount":"少々","Comment":""},{"Name":"片栗粉","Amount":"大さじ1杯","Comment":""},{"Name":"サラダ油","Amount":"適量","Comment":""},{"Name":"トッピング","Amount":"","Comment":""},{"Name":"中濃ソース","Amount":"適量","Comment":""}]}],"Steps":[{"Text":"油揚げは開きやすいように菜箸を転がします。包丁で横に切り込みを入れて、裏返します。","Images":null},{"Text":"豚こま肉は塩、こしょうで下味をつけて、片栗粉をまぶします。","Images":null},{"Text":"①の中に②を入れて切り口を折り返します。","Images":null},{"Text":"フライパンに深さ1cmほどのサラダ油を入れて熱し、③を入れて中火で揚げ焼きにします。","Images":null},{"Text":"焼き色がついたら裏返し、5〜8分揚げ焼きして中までしっかりと火を通します。","Images":null},{"Text":"食べやすい大きさに切って器に盛り付けたら完成です。お好みでソースをかけて召し上がれ。","Images":null}]}`,
	// "https://macaro-ni.jp/104802": `{"Title":"豚こまで作る♪白菜のとんぺい焼き","Image":"https://cdn.macaro-ni.jp/image/summary/104/104802/TJjkBPAVvCIAKGFJ6tkvngGe2lbUuGCfzGlvygIs.jpg?p=1x1","IngredientGroups":[{"Name":"","Children":[{"Name":"白菜","Amount":"180g","Comment":""},{"Name":"豚こま肉","Amount":"80g","Comment":""},{"Name":"もやし","Amount":"40g","Comment":""},{"Name":"めんつゆ","Amount":"小さじ2杯","Comment":"３倍濃縮"},{"Name":"味付塩こしょう","Amount":"少々","Comment":""},{"Name":"とろけるチーズ","Amount":"20g","Comment":""},{"Name":"卵","Amount":"3個","Comment":""},{"Name":"水溶き片栗粉","Amount":"片栗粉:小さじ2杯、水:小さじ2杯","Comment":""},{"Name":"サラダ油","Amount":"小さじ1杯×2","Comment":""},{"Name":"トッピング","Amount":"","Comment":""},{"Name":"お好み焼きソース","Amount":"適量","Comment":""},{"Name":"マヨネーズ","Amount":"適量","Comment":""},{"Name":"小口ねぎ","Amount":"適量","Comment":""},{"Name":"七味唐辛子","Amount":"適量","Comment":""}]}],"Steps":[{"Text":"白菜を1cm幅に切ります。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104802/vUImcG2miFkNjbvn0ehEL4fMJQiaFhDQmBZQH7BF.jpg"]},{"Text":"ボウルに卵、水溶き片栗粉を入れて混ぜ合わせます。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104802/jW7SHFJ8WvnB0wmkTzCtOvVePPlJSGw0sbsBWcbk.jpg"]},{"Text":"フライパンにサラダ油を引き中火で熱し、豚肉を炒めます。肉の色が変わったら白菜、もやしを加えて強火で1分ほど炒めます。味付塩こしょう、めんつゆを加えさっと炒め合わせ、いったん取り出します。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104802/KIv7kKx8FU9AAxE2gfym4E4GxxOcbdyNGfG2urfQ.jpg"]},{"Text":"フライパンにサラダ油を入れ中火で熱し、溶き卵を流し入れます。菜箸で軽く混ぜ、半熟状になったら、とろけるチーズと③を中央にのせます。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104802/xSA9nnKkkgD0I3CeoVHUC4GCDR8S9kSXB5FKX1Tz.jpg"]},{"Text":"具を包むように卵の両端を折りたたみます。折りたたんだ部分が下になるように皿に盛りつけます。ソース、マヨネーズ、七味唐辛子、小口ねぎをかけて完成です。","Images":["https://cdn.macaro-ni.jp/image/summary/104/104802/8oCfEGVMk14LAoYZ4WliIM1uYQUaBVETh6TDCvAy.jpg"]}]}`,
	// "https://macaro-ni.jp/94837":  `{"Title":"食べ応え抜群♪生姜焼き豚つくね","Image":"https://cdn.macaro-ni.jp/image/summary/94/94837/LxT9jnKHHTrKofxUxgGz9XEJMbbJcIuzRipox9IP.jpg?p=1x1","IngredientGroups":[{"Name":"","Children":[{"Name":"豚こま肉","Amount":"300g","Comment":""},{"Name":"玉ねぎ","Amount":"1/4個","Comment":""},{"Name":"しょうが","Amount":"1片(15g)","Comment":""},{"Name":"片栗粉","Amount":"大さじ2杯","Comment":""},{"Name":"酒","Amount":"大さじ1/2杯","Comment":""},{"Name":"塩","Amount":"少々","Comment":""},{"Name":"こしょう","Amount":"少々","Comment":""},{"Name":"サラダ油","Amount":"大さじ1/2杯","Comment":""},{"Name":"トッピング","Amount":"","Comment":""},{"Name":"白いりごま","Amount":"適量","Comment":""},{"Name":"小口ねぎ","Amount":"適量","Comment":""}]},{"Name":"a.","Children":[{"Name":"酒","Amount":"大さじ2杯","Comment":""},{"Name":"みりん","Amount":"大さじ2杯","Comment":""},{"Name":"砂糖","Amount":"小さじ1杯","Comment":""},{"Name":"はちみつ","Amount":"小さじ1杯","Comment":""},{"Name":"しょうゆ","Amount":"大さじ2杯","Comment":""}]}],"Steps":[{"Text":"豚こま肉は包丁で叩き、粗めのみじん切りにします。","Images":["https://cdn.macaro-ni.jp/image/summary/94/94837/RA6phTGBbz9j2DUC3csGGoNJGTN5tP81FLQGwVhI.jpg"]},{"Text":"ボウルに①、玉ねぎ、しょうが（半量）、塩、こしょう、酒、片栗粉を加えて粘りが出るまでよく混ぜ合わせます。","Images":["https://cdn.macaro-ni.jp/image/summary/94/94837/D7yU8wwASwViMQDBZ0XBHObJPziCzfJZMJtgf3g0.jpg"]},{"Text":"ひとつ分手に取り形を整えたら、サラダ油を熱したフライパンにのせて両面焼きます。焼き色がついたらフタをし、3〜4分蒸し焼きにして中までしっかり火を通します。","Images":["https://cdn.macaro-ni.jp/image/summary/94/94837/RpjdeV1LIZrRNXenOPvWJbklwQZQhSZFM7DtZX9e.jpg"]},{"Text":"(a)の調味料、残りのしょうがを加えて煮絡めます。器に盛り付けたら完成です。お好みでいりごま、小口ねぎをトッピングして召し上がれ。","Images":["https://cdn.macaro-ni.jp/image/summary/94/94837/QkkC4SN5xT9nAthgx9Qh7jfcO4CvP1ymU7VE7G5m.jpg"]}]}`,

}

func TestNewParser(t *testing.T) {
	ctx := context.Background()

	for url, want := range tests {
		url := url
		want := want

		t.Run(url, func(t *testing.T) {
			t.Parallel()

			rex, err := NewParser().Parse2(ctx, url)
			if err != nil {
				t.Fatal(err)
			}

			if err := sites.RecipeMustBe2(want, rex); err != nil {
				t.Error(err)
			}
		})
	}
}
